apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-prod