apiVersion: v2
name: jenkins
description: A Helm chart for Jenkins CI/CD with full automation
type: application
version: 0.1.0
appVersion: "2.516.1"

keywords:
  - ci/cd
  - jenkins
  - automation
  - devops

maintainers:
  - name: Casino Cloud App Team
    email: devops@casino-app.com

sources:
  - https://github.com/your-username/casino-cloud-app

# No dependencies - using standalone Jenkins deployment